defmodule Helpdesk.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :org_id, :bigint
    end

    alter table(:tickets) do
      add :org_id, :bigint
    end

    create table(:orgs_membership, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"

      add :user_id,
          references(:users,
            column: :id,
            name: "orgs_membership_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :org_id, :bigint
    end

    create table(:organizations, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:users) do
      modify :org_id,
             references(:organizations,
               column: :id,
               name: "users_org_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:tickets) do
      modify :org_id,
             references(:organizations,
               column: :id,
               name: "tickets_org_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:orgs_membership) do
      modify :org_id,
             references(:organizations,
               column: :id,
               name: "orgs_membership_org_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text
      add :slug, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :slug
      remove :name
    end

    drop constraint(:orgs_membership, "orgs_membership_org_id_fkey")

    alter table(:orgs_membership) do
      modify :org_id, :bigint
    end

    drop constraint(:tickets, "tickets_org_id_fkey")

    alter table(:tickets) do
      modify :org_id, :bigint
    end

    drop constraint(:users, "users_org_id_fkey")

    alter table(:users) do
      modify :org_id, :bigint
    end

    drop table(:organizations)

    drop constraint(:orgs_membership, "orgs_membership_user_id_fkey")

    drop table(:orgs_membership)

    alter table(:tickets) do
      remove :org_id
    end

    alter table(:users) do
      remove :org_id
    end
  end
end
